# 딥러닝 기본 개념

In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t.ndim)
print(t.shape)

1
(7,)


# tensorflow -> array 만들기

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


# eval() 쓰기 위해 session을 열어야함

In [4]:
sess = tf.InteractiveSession()

In [5]:
t1 = tf.constant([[1,2,3], [1,2,3]])
t1.eval()

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
t2 = tf.constant([[1,2,4,1,3,4,5],[4,4,6,14,3,3,3],[1,2,7,4,78,3,1]])
t2.eval()

array([[ 1,  2,  4,  1,  3,  4,  5],
       [ 4,  4,  6, 14,  3,  3,  3],
       [ 1,  2,  7,  4, 78,  3,  1]])

# matmul 사용(shape가 다르면 사용 불가)
- tf.matmul(a,b)라고 할 때 차원은 동일해야함
- a의 열과 b의 행이 동일해야함
- shape의 행은 a의 행과 일치하며, 열은 b의 열과 일치
- matmul(a(2,3), b(3,7))  --> shape는 (2,7)

In [7]:
tf.matmul(t1,t2).eval()

array([[ 12,  16,  37,  41, 243,  19,  14],
       [ 12,  16,  37,  41, 243,  19,  14]])

# boardcasting(shape가 다르더라도 사용가능)
- a와 b가 있다면 b(a보다 한차원 낮고 a의 나머지 차원과 b의 값이 일치해야함)
- a(1,3,5) + b(3,5) --> shape는 (1,3,5)

In [8]:
t3 = tf.constant([[[1,2,3], [1,2,3]],[[1,2,3], [1,2,3]]])
t3.eval()

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [9]:
t4 = tf.constant([ [1,2,3]])
t4.eval()

array([[1, 2, 3]])

In [10]:
(t3*t4).eval()

array([[[1, 4, 9],
        [1, 4, 9]],

       [[1, 4, 9],
        [1, 4, 9]]])

# reduce mean(평균 값을 구해줌)

In [11]:
tf.reduce_mean([1,2,3,5], axis=0).eval()

2

###### 1행과 2행의 평균을 각각 구하고 1행(1.5), 2행(3.5) 이 둘의 평균을 다시 구함 // (1.5+3.5)/2 = 2.5

In [12]:
x = [[1.,2.],[3.,4.]]
tf.reduce_mean(x).eval()

2.5

# axis = 0(행) // 1(열) 

In [13]:
# 1과 3의 평균 // 2와 4의 평균
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [14]:
# 1와 2의 평균 // 3과 4의 평균
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

###### 전체의 axis을 사용하지 않을 경우 전체 값의 합을 구해줌

In [15]:
tf.reduce_sum(x).eval()

10.0

In [186]:
# 1과 3의 합 // 2와 4의 합
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [187]:
# 1와 2의 합 // 3과 4의 합
tf.reduce_sum(x, axis=1).eval()

array([3., 7.], dtype=float32)

# 전체의 합을 구하고 평균을 구하는 방식

In [192]:
# (1과2의 합3, 3과 4의 합7) -> (3, 7) -> 3과 7의 평균 -> 5 
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

# Argmax 사용법

In [193]:
x = [[0,1,2], [2,1,0]]

In [196]:
# 비교해서 높은 축에 있는 값을 넣어주는 역할
# 0과 2 비교 시 -> 2가 크므로 1번째 인덱스 // 1과 1 비교 시 -> 동일하므로 0번째 인덱스 // 2와 0 비교시 -> 2가 크므로 0번째 인덱스
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [197]:
# 0과 1과 2 비교 시 -> 2가 크므로 2번째 인덱스 // 2와 1과 0 비교 시 -> 2가 크므로 0번째 인덱스
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [198]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

# reshape 사용법
- shape 전체 값을 곱한 약수는 모두 사용 가능
- 특정 차원에 -1을 하면 나머지 차원을 곱하고 남은 값으로 채워줌
- shape(8,6,2) -> reshape(3,-1,2) -> 8*6*2= 96 // 96/6 -> -1로 설정한 차원의 값은 16이됨

In [208]:
t = np.array([[[0, 1, 2], [3, 4, 5]],[[6, 7, 8], [9, 10, 11]]])
print(t)
print(t.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [207]:
t1 = tf.reshape(t, shape=[-1, 3]).eval()
print(t1)
print(t1.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [222]:
t2 = tf.reshape(t, shape=[2, -1, 2]).eval()
print(t2)
print(t2.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 3, 2)


# reshape(squeeze, expand)
- squeez -> n차원이 1일 때 차원을 줄여줌
- expand_dims -> dim의 값에 따라 차원을 늘려줌 0일 땐 가장 n차원 1일 땐 n-1차원... -1일 땐 1차원

In [261]:
x = np.array([[[0,1,2],[4,6,3],[4,6,3],[4,6,3]]])
print(x)
print(x.shape)

[[[0 1 2]
  [4 6 3]
  [4 6 3]
  [4 6 3]]]
(1, 4, 3)


In [262]:
a = tf.squeeze(x).eval()
print(a)
print(a.shape)

[[0 1 2]
 [4 6 3]
 [4 6 3]
 [4 6 3]]
(4, 3)


In [ ]:
x = np.array([[[0,1,2],[4,6,3]],[[0,1,2],[4,6,3]]])
print(x)
print(x.shape)

In [244]:
b1 = tf.expand_dims(x, -1).eval()
print(b1)
print(b1.shape)

[[[[0]
   [1]
   [2]]

  [[4]
   [6]
   [3]]]


 [[[0]
   [1]
   [2]]

  [[4]
   [6]
   [3]]]]
(2, 2, 3, 1)


In [242]:
b2 = tf.expand_dims(x, 0).eval()
print(b2)
print(b2.shape)

[[[[0 1 2]
   [4 6 3]]

  [[0 1 2]
   [4 6 3]]]]
(1, 2, 2, 3)


# One hot 인코딩
- depth의 크기에 따라 분포도가 달라지는데 depth이 n일 때 n개의 열을 가짐
- depth -> 8이라면 표현할 수 있는 n은 8개라고 생각하면됨

In [270]:
t = tf.one_hot([[0], [24], [18], [7]], depth=25).eval()
print(t)
print(t.shape)

[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
   0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0.]]]
(4, 1, 25)


In [280]:
# reshape을 통해 25개씩 펼쳐서 나타내고 싶다면 25개의 one hot을 1차원에 놓고 나머지 차원을 -1을 해주면 4,25로 reshape됨
t1 = tf.reshape(t, shape=[-1,25]).eval()
print(t1)
print(t1.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
(4, 25)


# Casting 사용법 
- cast을 int와 함께 쓰면 float 값이 내림해서 나타낼 수 있음
- 정답 데이터을 0과 1로 두었을 때 아래와 같이 정답이 몇개인지 확일 할 때 castg 함수를 사용하여 값을 표현할 수 있음

In [281]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [283]:
tf.cast([True, False, 1== 1, 0 == 6], tf.int32).eval()

array([1, 0, 1, 0])

# Stack
- stack 기본의 경우 순서대로 쌓아줌(단, shape가 동일해야함)
- stack에 axis를 적용 할 경우 axis = 0은 기본과 같음
- axis = 1의 경우 열과 행이 바뀐 shape 값이 도출되고 내용은 각 1행,...,n행이 한 열의 구성

In [292]:
x = [1, 4, 2, 5]
y = [2, 5, 4, 1]
z = [3, 6, 5, 3]

s = tf.stack([x, y, z]).eval()
print(s)
print(s.shape)

[[1 4 2 5]
 [2 5 4 1]
 [3 6 5 3]]
(3, 4)


In [293]:
s1 = tf.stack([x, y, z], axis=1).eval()
print(s1)
print(s1.shape)

[[1 2 3]
 [4 5 6]
 [2 4 5]
 [5 1 3]]
(4, 3)


# Ones and Zeros like
- tf.ones -> 각 행과 열 값을 1로 채워줌
- tf.zeros -> 각 행과 열 값을 0으로 채워줌

In [294]:
x = [[0, 1, 2], [2, 1, 0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [295]:
x = [[0, 1, 2], [2, 1, 0]]
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

# zip
- 다양한 tensor 값을 하나로 묶어서 각 인덱스의 data 값을 도출해줌

In [300]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [301]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
