# 여러가지의 그래프를 가지는 경우
- muti-variable이라고 함
- Hypothesis = w1x1 + w2x2 + w3x3 + wnxn + b
- Hypothesis는 matrix를 활용하여 구함
- x는 매트릭스(2차원)를 구성하고 w는 매트릭스의 열의 개수에 맞는 행을 구성
- x(a, b)라면 w(b, 1)를 구성  --> a를 인스턴스라고 지칭 // b를 매트릭스라 지칭
- X(5, 3) * W(3, 1) = H(X)(5, 1) 구성 // H(X)의 행은 x의 행과 일치
- -> 우리가 설계하는 부분은 W이므로 그 부분을 설계하는데 X의 열과 H(X)의 열의 갯수에 맞추면됨
- -> W의 행은 한개의 데이터 안에 있는 tensor 값을 지칭 // 열은 데이터가 들어가 최종 출력받고자하는 output 값을 지칭

# muti-variable 예제(매트릭스 변환 전)

In [49]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [50]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [51]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [52]:
w1 = tf.Variable(tf.random_normal([1]), name ="weight1")
w2 = tf.Variable(tf.random_normal([1]), name ="weight2")
w3 = tf.Variable(tf.random_normal([1]), name ="weight3")
b = tf.Variable(tf.random_normal([1]), name ="bias")

In [53]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [54]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [55]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [56]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [57]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPredction:\n", hy_val)

0 Cost:  19244.273 
Predction:
 [32.29232  33.843582 35.706963 40.842808 23.050652]
10 Cost:  14.917467 
Predction:
 [154.94896 181.29315 180.97836 199.0405  135.52324]
20 Cost:  14.672992 
Predction:
 [155.30669 181.74852 181.4139  199.51555 135.87624]
30 Cost:  14.604898 
Predction:
 [155.29443 181.7591  181.4112  199.5134  135.88998]
40 Cost:  14.537168 
Predction:
 [155.28108 181.76831 181.40721 199.50981 135.90266]
50 Cost:  14.469793 
Predction:
 [155.2678  181.77753 181.40323 199.50623 135.91531]
60 Cost:  14.402814 
Predction:
 [155.25453 181.78667 181.39925 199.50267 135.92793]
70 Cost:  14.336139 
Predction:
 [155.2413  181.79582 181.39528 199.49911 135.94052]
80 Cost:  14.269893 
Predction:
 [155.2281  181.80493 181.39133 199.49556 135.95305]
90 Cost:  14.203931 
Predction:
 [155.21497 181.81403 181.38739 199.492   135.96558]
100 Cost:  14.138346 
Predction:
 [155.20184 181.8231  181.38347 199.48848 135.97806]
110 Cost:  14.073084 
Predction:
 [155.18875 181.83214 181.37955 

1050 Cost:  9.26268 
Predction:
 [154.10776 182.57971 181.05661 199.18683 137.026  ]
1060 Cost:  9.223307 
Predction:
 [154.09772 182.58665 181.05362 199.18398 137.03572]
1070 Cost:  9.184179 
Predction:
 [154.08769 182.5936  181.05063 199.18115 137.0454 ]
1080 Cost:  9.145266 
Predction:
 [154.07771 182.60054 181.04767 199.17833 137.05504]
1090 Cost:  9.106556 
Predction:
 [154.06775 182.60744 181.0447  199.17552 137.06467]
1100 Cost:  9.068024 
Predction:
 [154.0578  182.6143  181.04175 199.17268 137.07426]
1110 Cost:  9.0297 
Predction:
 [154.0479  182.62117 181.0388  199.16988 137.08385]
1120 Cost:  8.991573 
Predction:
 [154.03801 182.628   181.03584 199.16707 137.0934 ]
1130 Cost:  8.953678 
Predction:
 [154.02815 182.63483 181.03291 199.16428 137.10292]
1140 Cost:  8.915943 
Predction:
 [154.01833 182.64165 181.03    199.16148 137.11243]
1150 Cost:  8.878423 
Predction:
 [154.00854 182.64844 181.02708 199.1587  137.12192]
1160 Cost:  8.841133 
Predction:
 [153.99875 182.65518 18

# muti-variable 예제(매트릭스 변환 후)

In [58]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

## 매트릭스 변환
- x_data 3개의 값(5열)을 5행 3열로 변환
- y_data 값(5열)을 5행으로 변환

## x_data 구성 측면에서 살펴보기
- 5행 인스턴스(data개수) -  5개
- 3열 data 내부 구조 - shape를 지칭 shape=(None,3) // None으로 표기 이유 -> vector(1차원)이므로  만약 matrix(2차원)라면 shape=[1,3] 

In [69]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96.,98., 100.], [73. , 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

## placeholder -> data를 맵핑하는 역할

## shape의 구성
- X(data)의 경우 shape는 data하나가 구성하고 있는 shape를 사용
- Y(output / 결과 값)의 경우 shape는 얻고자하는 정답 data의 갯수를 의미(정답 1개일 땐 1개 // 다수일 땐 다수개) 

In [77]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

## Variable -> data를 tensor로 변환

## W(가중치)의 shape만드는 방법
- 각각의 shape 값을 곱해주면됨 
- 예를 들어: data(3,5)라면 W는 열과 행을 반대로(5,3)로 만들어주어 가중치 적용

###### muti-variable를 활용 할 때는 X*W를 하는 것이 아니라 matmul을 활용하여 값이 적절하게 곱해질 수 있게 만들어줌(broadcasting과 차이 파악)

In [78]:
W = tf.Variable(tf.random_normal([3, 1]), name ="weight1")
b = tf.Variable(tf.random_normal([1]), name ="bias")

In [79]:
hypothesis = tf.matmul(X, W) + b

In [80]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [81]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [82]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [83]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPredction:\n", hy_val)

0 Cost:  287578.4 
Predction:
 [[-325.62424]
 [-386.3157 ]
 [-383.16507]
 [-418.34888]
 [-292.4953 ]]
10 Cost:  4.060657 
Predction:
 [[148.7662 ]
 [183.85829]
 [178.64124]
 [193.44376]
 [142.40216]]
20 Cost:  1.4215443 
Predction:
 [[150.20573]
 [185.58057]
 [180.34233]
 [195.29587]
 [143.71414]]
30 Cost:  1.4150846 
Predction:
 [[150.21425]
 [185.58292]
 [180.34874]
 [195.30254]
 [143.71425]]
40 Cost:  1.4087032 
Predction:
 [[150.2184 ]
 [185.58006]
 [180.35   ]
 [195.30357]
 [143.71039]]
50 Cost:  1.4023292 
Predction:
 [[150.22255]
 [185.5772 ]
 [180.35126]
 [195.30463]
 [143.70653]]
60 Cost:  1.3960025 
Predction:
 [[150.2267 ]
 [185.57436]
 [180.35251]
 [195.30563]
 [143.70268]]
70 Cost:  1.3897079 
Predction:
 [[150.23083]
 [185.57152]
 [180.35378]
 [195.30667]
 [143.69885]]
80 Cost:  1.3834546 
Predction:
 [[150.23495]
 [185.5687 ]
 [180.35501]
 [195.3077 ]
 [143.69504]]
90 Cost:  1.3772324 
Predction:
 [[150.23903]
 [185.56586]
 [180.35625]
 [195.30873]
 [143.69121]]
100 Cost

1230 Cost:  0.8483163 
Predction:
 [[150.63998]
 [185.28952]
 [180.47719]
 [195.41066]
 [143.31647]]
1240 Cost:  0.84496915 
Predction:
 [[150.64297]
 [185.28748]
 [180.47812]
 [195.41145]
 [143.31366]]
1250 Cost:  0.8416441 
Predction:
 [[150.64595]
 [185.28542]
 [180.479  ]
 [195.41222]
 [143.31087]]
1260 Cost:  0.8383217 
Predction:
 [[150.64894]
 [185.28339]
 [180.47992]
 [195.41301]
 [143.30807]]
1270 Cost:  0.83503264 
Predction:
 [[150.65189]
 [185.28131]
 [180.4808 ]
 [195.41376]
 [143.30528]]
1280 Cost:  0.83174115 
Predction:
 [[150.65485]
 [185.27927]
 [180.48167]
 [195.41452]
 [143.30249]]
1290 Cost:  0.82847536 
Predction:
 [[150.6578 ]
 [185.27724]
 [180.48256]
 [195.4153 ]
 [143.29973]]
1300 Cost:  0.82523215 
Predction:
 [[150.66074]
 [185.27522]
 [180.48344]
 [195.41606]
 [143.29695]]
1310 Cost:  0.8220043 
Predction:
 [[150.66367]
 [185.2732 ]
 [180.48431]
 [195.41681]
 [143.29419]]
1320 Cost:  0.8187955 
Predction:
 [[150.6666 ]
 [185.27116]
 [180.48521]
 [195.41757]

# 예제를 통한 예측해 보기

In [84]:
print("your score will be ", sess.run(hypothesis,
                                     feed_dict={X: [[100., 70., 101.]]}))

your score will be  [[188.17136]]


In [85]:
print("your score will be ", sess.run(hypothesis,
                                     feed_dict={X: [[60., 70., 110.], [90., 100., 80.]]}))

your score will be  [[139.17555]
 [183.17192]]
