# 오버피팅
- overfitting은 learning rate의 크기에 따라 발생하는 경우가 많음
- learning rate 값이 큰 경우 -> 오버 슈팅 발생(오차 값의 편차가 심해짐)
- learning rate 값이 작은 경우 -> 학습의 길이가 길어지거나 국지적으로 최소 값을 도출해냄
- learning rate의 정답은 없지만 DATA 값에 따라 적절한 값을 넣어야 오버피팅을 방지할 수 있음

#  overfitting 방지
- 오버피팅 시 train data set을 더 추가
- 중복된 feature(column)을 제거해줌
- regularization 해주는 방법

# Regularization
- 큰 숫자의 가중치를 주지 않아야함

# 정규화 예제

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x_data = [[1,2,1], [1,3,2], [1,3,4], [1,5,5], [1,7,5], [1,2,5], [1,6,6], [1,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

In [3]:
x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

In [4]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [5]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
    print(step, cost_val, W_val)

0 9.782477 [[-2.1092706  -0.73131496 -1.8627356 ]
 [ 1.2814914  -1.1613019   1.3587868 ]
 [-0.12450868 -1.0437053   0.9309292 ]]
1 6.2427044 [[-2.0850246  -0.69387686 -1.9244198 ]
 [ 1.4422255  -0.98642635  1.0231773 ]
 [ 0.03689935 -0.8562681   0.5820839 ]]
2 4.805051 [[-2.0708416  -0.6566813  -1.9757985 ]
 [ 1.557497   -0.8120457   0.733525  ]
 [ 0.15937161 -0.6690888   0.2724323 ]]
3 3.6099713 [[-2.1187794  -0.6201523  -1.9643896 ]
 [ 1.3574715  -0.6390494   0.7605543 ]
 [-0.02406782 -0.4827465   0.26952946]]
4 2.6399574 [[-2.1351075  -0.58492434 -1.9832895 ]
 [ 1.3031795  -0.46888244  0.64467925]
 [-0.05980745 -0.29846835  0.12099094]]
5 1.8116605 [[-2.1651108  -0.5538101  -1.9844003 ]
 [ 1.1752857  -0.30811012  0.6118007 ]
 [-0.16902235 -0.12438328  0.05612077]]
6 1.3314946 [[-2.1797488  -0.53255755 -1.991015  ]
 [ 1.1198287  -0.1720847   0.5312322 ]
 [-0.2067608   0.01713858 -0.04766265]]
7 1.1980906 [[-2.1952055  -0.52862054 -1.9794954 ]
 [ 1.0484684  -0.08897178  0.5194796 ]
 [

77 0.7303289 [[-2.4357946  -1.1644646  -1.103062  ]
 [ 0.6973773   0.29041138  0.49118835]
 [ 0.21418104  0.0139994  -0.4654651 ]]
78 0.7273896 [[-2.4392767  -1.170099   -1.0939454 ]
 [ 0.695097    0.29329008  0.49058995]
 [ 0.21804519  0.01366921 -0.46899906]]
79 0.72450626 [[-2.442761   -1.175658   -1.0849022 ]
 [ 0.69287497  0.29611582  0.48998627]
 [ 0.22184916  0.01336026 -0.47249407]]
80 0.72167766 [[-2.446247   -1.1811424  -1.0759315 ]
 [ 0.69071007  0.29888955  0.48937747]
 [ 0.22559391  0.0130722  -0.47595078]]
81 0.7189021 [[-2.4497352  -1.1865535  -1.0670325 ]
 [ 0.68860126  0.30161208  0.48876375]
 [ 0.22928053  0.01280454 -0.47936973]]
82 0.7161783 [[-2.453225   -1.191892   -1.058204  ]
 [ 0.6865476   0.30428427  0.48814526]
 [ 0.23291004  0.01255681 -0.48275152]]
83 0.713505 [[-2.4567165  -1.1971592  -1.0494453 ]
 [ 0.6845479   0.306907    0.4875222 ]
 [ 0.23648342  0.01232859 -0.48609668]]
84 0.7108809 [[-2.4602096  -1.202356   -1.0407553 ]
 [ 0.6826013   0.30948105  0.4

179 0.5769228 [[-2.7881258  -1.4855869  -0.4296069 ]
 [ 0.6268404   0.4271208   0.42501605]
 [ 0.4355807   0.02946438 -0.7023296 ]]
180 0.5761193 [[-2.791456   -1.4871638  -0.42469984]
 [ 0.626849    0.42767572  0.42445254]
 [ 0.436943    0.02972621 -0.7039537 ]]
181 0.57532203 [[-2.7947829  -1.4887226  -0.41981423]
 [ 0.62686104  0.42822427  0.42389193]
 [ 0.43829972  0.02998666 -0.7055708 ]]
182 0.5745311 [[-2.7981064  -1.4902635  -0.4149498 ]
 [ 0.62687653  0.4287665   0.4233342 ]
 [ 0.439651    0.03024561 -0.7071811 ]]
183 0.5737461 [[-2.8014266  -1.4917867  -0.4101064 ]
 [ 0.6268953   0.42930254  0.42277938]
 [ 0.44099703  0.03050307 -0.7087846 ]]
184 0.57296705 [[-2.8047435  -1.4932926  -0.40528378]
 [ 0.62691724  0.42983255  0.42222744]
 [ 0.4423379   0.03075899 -0.7103813 ]]
185 0.57219386 [[-2.8080568  -1.4947811  -0.40048176]
 [ 0.6269422   0.4303566   0.42167842]
 [ 0.4436737   0.03101338 -0.7119715 ]]
186 0.57142645 [[-2.8113668  -1.4962528  -0.39570013]
 [ 0.6269701   0.43

In [9]:
print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))

Prediction: [2 2 2]


In [10]:
print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

Accuracy: 1.0


# Non-normalized inputs

In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [12]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
             [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
             [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
             [816, 820.9589984, 1008100, 815.48999, 819.23999],
             [819359985, 823, 1188100, 818.469971, 818.97998],
             [819, 823, 1198100, 816, 820.450012],
             [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

###### 모든 값을 일정하게 정규화 해주는 함수 MinMaxScaler
- 사용방법 MinMaxScaler() 호출한 뒤 fit_transform를 활용하여 정규화해야함
- 바로 MinMaxScaler 사용할 시 타입이 array가 아니므로 사용에 제약이 생김

In [13]:
scaler = MinMaxScaler()

In [14]:
xy = scaler.fit_transform(xy)

In [15]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

###### shape 값이 5인데 4를 넣어야하는 이유는 x_data의 인덱스가 마지막 한개 제외하고 있으므로 4개가 됨

In [16]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 1])
W = tf.Variable(tf.random_normal([4,1]), name = "Weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [17]:
hypothesis = tf.matmul(X, W)+b
cost = tf.reduce_mean(-tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [19]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  -1.4937048 
Prediction:
 [[ 0.16238946]
 [-1.4024408 ]
 [-0.8564511 ]
 [-0.27986687]
 [-0.1325174 ]
 [-0.57571363]
 [-0.5437552 ]
 [-1.1946577 ]]
1 Cost:  -1.4937915 
Prediction:
 [[ 0.16234505]
 [-1.4024899 ]
 [-0.85649204]
 [-0.27989894]
 [-0.13255572]
 [-0.5757494 ]
 [-0.54378223]
 [-1.1946867 ]]
2 Cost:  -1.4938781 
Prediction:
 [[ 0.16230065]
 [-1.4025391 ]
 [-0.85653305]
 [-0.279931  ]
 [-0.13259402]
 [-0.5757853 ]
 [-0.5438093 ]
 [-1.1947155 ]]
3 Cost:  -1.4939649 
Prediction:
 [[ 0.16225624]
 [-1.4025884 ]
 [-0.85657406]
 [-0.27996308]
 [-0.13263237]
 [-0.57582116]
 [-0.54383636]
 [-1.1947446 ]]
4 Cost:  -1.4940513 
Prediction:
 [[ 0.1622119 ]
 [-1.4026375 ]
 [-0.8566151 ]
 [-0.27999514]
 [-0.13267064]
 [-0.57585686]
 [-0.5438634 ]
 [-1.1947734 ]]
5 Cost:  -1.494138 
Prediction:
 [[ 0.16216749]
 [-1.4026866 ]
 [-0.8566562 ]
 [-0.28002724]
 [-0.13270897]
 [-0.57589275]
 [-0.54389054]
 [-1.1948024 ]]
6 Cost:  -1.4942248 
Prediction:
 [[ 0.16212308]
 [-1.4027358 ]
 [-0.85

98 Cost:  -1.5022216 
Prediction:
 [[ 0.15803277]
 [-1.4072673 ]
 [-0.8604753 ]
 [-0.28301448]
 [-0.13627675]
 [-0.57922804]
 [-0.54641116]
 [-1.1974976 ]]
99 Cost:  -1.5023087 
Prediction:
 [[ 0.15798825]
 [-1.4073167 ]
 [-0.8605164 ]
 [-0.28304663]
 [-0.13631517]
 [-0.5792639 ]
 [-0.54643834]
 [-1.1975267 ]]
100 Cost:  -1.5023959 
Prediction:
 [[ 0.15794367]
 [-1.407366  ]
 [-0.86055756]
 [-0.2830788 ]
 [-0.13635361]
 [-0.5792998 ]
 [-0.54646546]
 [-1.1975557 ]]
101 Cost:  -1.502483 
Prediction:
 [[ 0.15789914]
 [-1.4074153 ]
 [-0.8605987 ]
 [-0.28311098]
 [-0.136392  ]
 [-0.5793358 ]
 [-0.5464926 ]
 [-1.1975846 ]]
102 Cost:  -1.5025702 
Prediction:
 [[ 0.15785462]
 [-1.4074645 ]
 [-0.86063987]
 [-0.28314313]
 [-0.13643044]
 [-0.5793717 ]
 [-0.54651976]
 [-1.1976137 ]]
103 Cost:  -1.5026574 
Prediction:
 [[ 0.15781009]
 [-1.4075139 ]
 [-0.860681  ]
 [-0.28317532]
 [-0.13646886]
 [-0.57940763]
 [-0.5465469 ]
 [-1.1976427 ]]
104 Cost:  -1.5027446 
Prediction:
 [[ 0.15776557]
 [-1.40756

236 Cost:  -1.5143111 
Prediction:
 [[ 0.1518735 ]
 [-1.4140929 ]
 [-0.86616564]
 [-0.2874644 ]
 [-0.14159241]
 [-0.5841969 ]
 [-0.5501662 ]
 [-1.2015132 ]]
237 Cost:  -1.5143989 
Prediction:
 [[ 0.15182877]
 [-1.4141424 ]
 [-0.8662069 ]
 [-0.28749672]
 [-0.14163107]
 [-0.5842329 ]
 [-0.5501934 ]
 [-1.2015424 ]]
238 Cost:  -1.514487 
Prediction:
 [[ 0.151784  ]
 [-1.4141922 ]
 [-0.86624825]
 [-0.28752908]
 [-0.14166972]
 [-0.58426905]
 [-0.5502207 ]
 [-1.2015715 ]]
239 Cost:  -1.514575 
Prediction:
 [[ 0.15173918]
 [-1.4142418 ]
 [-0.8662897 ]
 [-0.28756142]
 [-0.14170837]
 [-0.5843052 ]
 [-0.550248  ]
 [-1.2016008 ]]
240 Cost:  -1.5146632 
Prediction:
 [[ 0.15169442]
 [-1.4142914 ]
 [-0.86633104]
 [-0.28759378]
 [-0.14174706]
 [-0.58434135]
 [-0.5502753 ]
 [-1.2016299 ]]
241 Cost:  -1.5147514 
Prediction:
 [[ 0.15164965]
 [-1.414341  ]
 [-0.86637247]
 [-0.28762612]
 [-0.14178574]
 [-0.5843775 ]
 [-0.5503026 ]
 [-1.2016592 ]]
242 Cost:  -1.5148394 
Prediction:
 [[ 0.15160489]
 [-1.4143

374 Cost:  -1.5265148 
Prediction:
 [[ 0.14568475]
 [-1.420952  ]
 [-0.87188363]
 [-0.29193562]
 [-0.14693567]
 [-0.58918977]
 [-0.5539392 ]
 [-1.2055483 ]]
375 Cost:  -1.5266035 
Prediction:
 [[ 0.14563978]
 [-1.4210018 ]
 [-0.8719251 ]
 [-0.2919681 ]
 [-0.1469745 ]
 [-0.589226  ]
 [-0.5539666 ]
 [-1.2055776 ]]
376 Cost:  -1.5266922 
Prediction:
 [[ 0.1455948 ]
 [-1.4210515 ]
 [-0.8719666 ]
 [-0.2920006 ]
 [-0.14701334]
 [-0.58926225]
 [-0.553994  ]
 [-1.2056068 ]]
377 Cost:  -1.5267811 
Prediction:
 [[ 0.14554983]
 [-1.4211013 ]
 [-0.87200814]
 [-0.29203305]
 [-0.14705211]
 [-0.58929855]
 [-0.5540214 ]
 [-1.2056361 ]]
378 Cost:  -1.52687 
Prediction:
 [[ 0.14550486]
 [-1.421151  ]
 [-0.8720497 ]
 [-0.29206556]
 [-0.14709094]
 [-0.58933485]
 [-0.55404884]
 [-1.2056655 ]]
379 Cost:  -1.5269588 
Prediction:
 [[ 0.14545989]
 [-1.421201  ]
 [-0.8720912 ]
 [-0.29209805]
 [-0.14712974]
 [-0.5893711 ]
 [-0.5540762 ]
 [-1.2056947 ]]
380 Cost:  -1.5270476 
Prediction:
 [[ 0.14541492]
 [-1.4212

500 Cost:  -1.5377479 
Prediction:
 [[ 0.1400091 ]
 [-1.427236  ]
 [-0.87712383]
 [-0.29603538]
 [-0.1518332 ]
 [-0.59376657]
 [-0.55739796]
 [-1.2092453 ]]
501 Cost:  -1.5378375 
Prediction:
 [[ 0.13996398]
 [-1.4272859 ]
 [-0.87716556]
 [-0.29606798]
 [-0.15187213]
 [-0.593803  ]
 [-0.5574255 ]
 [-1.2092748 ]]
502 Cost:  -1.5379272 
Prediction:
 [[ 0.1399188 ]
 [-1.427336  ]
 [-0.87720716]
 [-0.2961006 ]
 [-0.15191108]
 [-0.5938394 ]
 [-0.55745304]
 [-1.2093041 ]]
503 Cost:  -1.5380163 
Prediction:
 [[ 0.13987362]
 [-1.4273858 ]
 [-0.87724876]
 [-0.29613322]
 [-0.15195006]
 [-0.59387577]
 [-0.5574805 ]
 [-1.2093335 ]]
504 Cost:  -1.538106 
Prediction:
 [[ 0.1398285 ]
 [-1.4274359 ]
 [-0.8772905 ]
 [-0.29616582]
 [-0.15198904]
 [-0.59391224]
 [-0.557508  ]
 [-1.209363  ]]
505 Cost:  -1.5381956 
Prediction:
 [[ 0.13978332]
 [-1.4274858 ]
 [-0.87733215]
 [-0.29619843]
 [-0.15202802]
 [-0.5939486 ]
 [-0.5575355 ]
 [-1.2093923 ]]
506 Cost:  -1.5382851 
Prediction:
 [[ 0.13973814]
 [-1.427

625 Cost:  -1.5489882 
Prediction:
 [[ 0.13435447]
 [-1.4334984 ]
 [-0.88234556]
 [-0.30012003]
 [-0.15671587]
 [-0.5983269 ]
 [-0.5608442 ]
 [-1.2129295 ]]
626 Cost:  -1.5490785 
Prediction:
 [[ 0.1343092 ]
 [-1.4335486 ]
 [-0.8823874 ]
 [-0.30015275]
 [-0.15675497]
 [-0.5983635 ]
 [-0.5608718 ]
 [-1.212959  ]]
627 Cost:  -1.5491688 
Prediction:
 [[ 0.13426387]
 [-1.4335989 ]
 [-0.88242924]
 [-0.3001855 ]
 [-0.1567941 ]
 [-0.5984    ]
 [-0.5608994 ]
 [-1.2129886 ]]
628 Cost:  -1.549259 
Prediction:
 [[ 0.13421854]
 [-1.4336491 ]
 [-0.8824711 ]
 [-0.30021825]
 [-0.15683326]
 [-0.5984366 ]
 [-0.56092703]
 [-1.2130181 ]]
629 Cost:  -1.5493495 
Prediction:
 [[ 0.13417315]
 [-1.4336994 ]
 [-0.8825129 ]
 [-0.300251  ]
 [-0.15687245]
 [-0.59847313]
 [-0.5609547 ]
 [-1.2130476 ]]
630 Cost:  -1.5494398 
Prediction:
 [[ 0.13412783]
 [-1.4337496 ]
 [-0.8825549 ]
 [-0.30028376]
 [-0.15691161]
 [-0.5985097 ]
 [-0.5609823 ]
 [-1.2130772 ]]
631 Cost:  -1.5495301 
Prediction:
 [[ 0.13408244]
 [-1.433

755 Cost:  -1.5607798 
Prediction:
 [[ 0.12844744]
 [-1.4400411 ]
 [-0.88780063]
 [-0.30438682]
 [-0.16181576]
 [-0.6030908 ]
 [-0.56444395]
 [-1.2167779 ]]
756 Cost:  -1.560871 
Prediction:
 [[ 0.12840194]
 [-1.4400915 ]
 [-0.88784266]
 [-0.30441973]
 [-0.16185504]
 [-0.60312754]
 [-0.56447166]
 [-1.2168076 ]]
757 Cost:  -1.560962 
Prediction:
 [[ 0.12835637]
 [-1.4401418 ]
 [-0.8878847 ]
 [-0.3044526 ]
 [-0.16189438]
 [-0.6031642 ]
 [-0.56449944]
 [-1.2168373 ]]
758 Cost:  -1.561053 
Prediction:
 [[ 0.12831086]
 [-1.4401922 ]
 [-0.8879267 ]
 [-0.3044855 ]
 [-0.16193366]
 [-0.6032009 ]
 [-0.56452715]
 [-1.216867  ]]
759 Cost:  -1.5611441 
Prediction:
 [[ 0.12826535]
 [-1.4402426 ]
 [-0.8879688 ]
 [-0.3045184 ]
 [-0.161973  ]
 [-0.6032377 ]
 [-0.5645549 ]
 [-1.2168965 ]]
760 Cost:  -1.5612353 
Prediction:
 [[ 0.12821978]
 [-1.4402931 ]
 [-0.8880108 ]
 [-0.3045513 ]
 [-0.16201228]
 [-0.60327435]
 [-0.5645827 ]
 [-1.2169262 ]]
761 Cost:  -1.5613263 
Prediction:
 [[ 0.12817428]
 [-1.44034

880 Cost:  -1.5722086 
Prediction:
 [[ 0.12274262]
 [-1.4463534 ]
 [-0.8930652 ]
 [-0.30850673]
 [-0.16674045]
 [-0.6076895 ]
 [-0.567919  ]
 [-1.220491  ]]
881 Cost:  -1.5723003 
Prediction:
 [[ 0.12269691]
 [-1.4464039 ]
 [-0.8931074 ]
 [-0.30853975]
 [-0.16677994]
 [-0.60772634]
 [-0.56794685]
 [-1.2205209 ]]
882 Cost:  -1.5723921 
Prediction:
 [[ 0.12265119]
 [-1.4464545 ]
 [-0.8931496 ]
 [-0.3085728 ]
 [-0.1668194 ]
 [-0.6077632 ]
 [-0.56797475]
 [-1.2205505 ]]
883 Cost:  -1.572484 
Prediction:
 [[ 0.12260547]
 [-1.4465051 ]
 [-0.8931918 ]
 [-0.3086058 ]
 [-0.16685888]
 [-0.60780007]
 [-0.5680026 ]
 [-1.2205803 ]]
884 Cost:  -1.5725757 
Prediction:
 [[ 0.12255976]
 [-1.4465556 ]
 [-0.893234  ]
 [-0.30863884]
 [-0.16689831]
 [-0.6078369 ]
 [-0.5680304 ]
 [-1.2206101 ]]
885 Cost:  -1.5726675 
Prediction:
 [[ 0.12251404]
 [-1.4466062 ]
 [-0.89327615]
 [-0.30867186]
 [-0.1669378 ]
 [-0.6078738 ]
 [-0.5680583 ]
 [-1.2206398 ]]
886 Cost:  -1.5727594 
Prediction:
 [[ 0.12246832]
 [-1.446

1014 Cost:  -1.5845677 
Prediction:
 [[ 0.11660042]
 [-1.4531509 ]
 [-0.8987342 ]
 [-0.31294262]
 [-0.17204383]
 [-0.6126411 ]
 [-0.57166064]
 [-1.2244895 ]]
1015 Cost:  -1.5846603 
Prediction:
 [[ 0.1165545 ]
 [-1.4532018 ]
 [-0.89877665]
 [-0.31297576]
 [-0.1720835 ]
 [-0.6126782 ]
 [-0.57168865]
 [-1.2245194 ]]
1016 Cost:  -1.5847532 
Prediction:
 [[ 0.11650857]
 [-1.4532526 ]
 [-0.8988191 ]
 [-0.31300893]
 [-0.17212313]
 [-0.6127151 ]
 [-0.57171667]
 [-1.2245493 ]]
1017 Cost:  -1.5848457 
Prediction:
 [[ 0.11646265]
 [-1.4533035 ]
 [-0.8988614 ]
 [-0.3130421 ]
 [-0.1721628 ]
 [-0.6127522 ]
 [-0.5717446 ]
 [-1.2245792 ]]
1018 Cost:  -1.5849384 
Prediction:
 [[ 0.11641672]
 [-1.4533545 ]
 [-0.89890385]
 [-0.31307527]
 [-0.17220247]
 [-0.6127893 ]
 [-0.5717726 ]
 [-1.2246091 ]]
1019 Cost:  -1.5850312 
Prediction:
 [[ 0.1163708 ]
 [-1.4534053 ]
 [-0.8989462 ]
 [-0.31310844]
 [-0.1722421 ]
 [-0.6128262 ]
 [-0.5718006 ]
 [-1.224639  ]]
1020 Cost:  -1.5851239 
Prediction:
 [[ 0.11632487]


1149 Cost:  -1.5971327 
Prediction:
 [[ 0.11038396]
 [-1.4600315 ]
 [-0.9044721 ]
 [-0.31743205]
 [-0.17741182]
 [-0.6176528 ]
 [-0.57544756]
 [-1.2285365 ]]
1150 Cost:  -1.5972261 
Prediction:
 [[ 0.11033779]
 [-1.4600825 ]
 [-0.9045148 ]
 [-0.3174654 ]
 [-0.17745167]
 [-0.61768997]
 [-0.57547563]
 [-1.2285664 ]]
1151 Cost:  -1.5973198 
Prediction:
 [[ 0.11029163]
 [-1.4601338 ]
 [-0.9045573 ]
 [-0.3174987 ]
 [-0.17749152]
 [-0.61772716]
 [-0.57550377]
 [-1.2285966 ]]
1152 Cost:  -1.5974131 
Prediction:
 [[ 0.11024553]
 [-1.4601847 ]
 [-0.9045999 ]
 [-0.31753203]
 [-0.17753139]
 [-0.61776435]
 [-0.57553184]
 [-1.2286265 ]]
1153 Cost:  -1.5975065 
Prediction:
 [[ 0.11019936]
 [-1.4602356 ]
 [-0.9046425 ]
 [-0.31756538]
 [-0.17757127]
 [-0.6178016 ]
 [-0.57556   ]
 [-1.2286565 ]]
1154 Cost:  -1.5976002 
Prediction:
 [[ 0.1101532 ]
 [-1.4602869 ]
 [-0.904685  ]
 [-0.3175987 ]
 [-0.17761111]
 [-0.6178388 ]
 [-0.5755881 ]
 [-1.2286867 ]]
1155 Cost:  -1.5976937 
Prediction:
 [[ 0.11010709]


1275 Cost:  -1.6089559 
Prediction:
 [[ 0.10455596]
 [-1.4664756 ]
 [-0.9098477 ]
 [-0.32164013]
 [-0.18244404]
 [-0.6223491 ]
 [-0.57899624]
 [-1.2323267 ]]
1276 Cost:  -1.60905 
Prediction:
 [[ 0.10450965]
 [-1.4665269 ]
 [-0.9098903 ]
 [-0.32167357]
 [-0.18248403]
 [-0.6223864 ]
 [-0.57902443]
 [-1.232357  ]]
1277 Cost:  -1.609144 
Prediction:
 [[ 0.10446328]
 [-1.466578  ]
 [-0.9099331 ]
 [-0.321707  ]
 [-0.18252403]
 [-0.6224237 ]
 [-0.5790527 ]
 [-1.2323871 ]]
1278 Cost:  -1.6092384 
Prediction:
 [[ 0.10441697]
 [-1.4666293 ]
 [-0.9099759 ]
 [-0.3217405 ]
 [-0.18256402]
 [-0.6224611 ]
 [-0.57908094]
 [-1.2324172 ]]
1279 Cost:  -1.6093326 
Prediction:
 [[ 0.10437059]
 [-1.4666804 ]
 [-0.91001856]
 [-0.32177395]
 [-0.18260401]
 [-0.6224984 ]
 [-0.57910913]
 [-1.2324474 ]]
1280 Cost:  -1.6094266 
Prediction:
 [[ 0.10432428]
 [-1.4667317 ]
 [-0.91006124]
 [-0.3218074 ]
 [-0.18264404]
 [-0.6225357 ]
 [-0.5791373 ]
 [-1.2324775 ]]
1281 Cost:  -1.6095209 
Prediction:
 [[ 0.10427791]
 [-

1410 Cost:  -1.6217366 
Prediction:
 [[ 0.09828427]
 [-1.473413  ]
 [-0.9156339 ]
 [-0.32616872]
 [-0.18785933]
 [-0.6274036 ]
 [-0.5828155 ]
 [-1.236407  ]]
1411 Cost:  -1.6218319 
Prediction:
 [[ 0.09823766]
 [-1.4734646 ]
 [-0.91567695]
 [-0.32620236]
 [-0.18789956]
 [-0.62744117]
 [-0.5828439 ]
 [-1.2364374 ]]
1412 Cost:  -1.621927 
Prediction:
 [[ 0.09819105]
 [-1.4735161 ]
 [-0.91571987]
 [-0.326236  ]
 [-0.18793985]
 [-0.6274787 ]
 [-0.5828723 ]
 [-1.2364677 ]]
1413 Cost:  -1.622022 
Prediction:
 [[ 0.0981445 ]
 [-1.4735676 ]
 [-0.9157629 ]
 [-0.32626963]
 [-0.18798009]
 [-0.6275163 ]
 [-0.58290064]
 [-1.236498  ]]
1414 Cost:  -1.6221175 
Prediction:
 [[ 0.09809795]
 [-1.4736192 ]
 [-0.9158058 ]
 [-0.3263033 ]
 [-0.18802032]
 [-0.6275538 ]
 [-0.582929  ]
 [-1.2365283 ]]
1415 Cost:  -1.6222125 
Prediction:
 [[ 0.09805134]
 [-1.4736707 ]
 [-0.91584885]
 [-0.32633692]
 [-0.18806061]
 [-0.6275914 ]
 [-0.5829574 ]
 [-1.2365587 ]]
1416 Cost:  -1.6223078 
Prediction:
 [[ 0.09800473]
 [

1538 Cost:  -1.6339624 
Prediction:
 [[ 0.09231061]
 [-1.4800198 ]
 [-0.9211447 ]
 [-0.33048192]
 [-0.19301975]
 [-0.63221765]
 [-0.58645296]
 [-1.2402928 ]]
1539 Cost:  -1.6340581 
Prediction:
 [[ 0.09226385]
 [-1.4800715 ]
 [-0.9211878 ]
 [-0.33051568]
 [-0.19306013]
 [-0.6322553 ]
 [-0.58648145]
 [-1.2403232 ]]
1540 Cost:  -1.6341543 
Prediction:
 [[ 0.09221709]
 [-1.4801233 ]
 [-0.921231  ]
 [-0.33054945]
 [-0.19310057]
 [-0.63229305]
 [-0.5865099 ]
 [-1.2403536 ]]
1541 Cost:  -1.63425 
Prediction:
 [[ 0.09217033]
 [-1.480175  ]
 [-0.92127407]
 [-0.3305832 ]
 [-0.19314095]
 [-0.6323308 ]
 [-0.5865384 ]
 [-1.2403841 ]]
1542 Cost:  -1.634346 
Prediction:
 [[ 0.09212357]
 [-1.4802268 ]
 [-0.9213173 ]
 [-0.330617  ]
 [-0.19318134]
 [-0.63236845]
 [-0.58656687]
 [-1.2404144 ]]
1543 Cost:  -1.6344419 
Prediction:
 [[ 0.09207675]
 [-1.4802784 ]
 [-0.9213604 ]
 [-0.33065075]
 [-0.19322175]
 [-0.6324061 ]
 [-0.5865953 ]
 [-1.2404448 ]]
1544 Cost:  -1.6345378 
Prediction:
 [[ 0.09202999]
 [-

1667 Cost:  -1.6463817 
Prediction:
 [[ 0.08626416]
 [-1.4867008 ]
 [-0.92671883]
 [-0.33484685]
 [-0.19824013]
 [-0.63708824]
 [-0.5901332 ]
 [-1.2442222 ]]
1668 Cost:  -1.6464782 
Prediction:
 [[ 0.08621719]
 [-1.4867525 ]
 [-0.9267621 ]
 [-0.33488074]
 [-0.19828069]
 [-0.6371261 ]
 [-0.59016174]
 [-1.2442527 ]]
1669 Cost:  -1.646575 
Prediction:
 [[ 0.08617023]
 [-1.4868046 ]
 [-0.9268054 ]
 [-0.33491462]
 [-0.19832122]
 [-0.6371639 ]
 [-0.59019035]
 [-1.2442832 ]]
1670 Cost:  -1.6466717 
Prediction:
 [[ 0.08612326]
 [-1.4868563 ]
 [-0.9268487 ]
 [-0.33494854]
 [-0.19836175]
 [-0.63720167]
 [-0.5902189 ]
 [-1.2443137 ]]
1671 Cost:  -1.6467683 
Prediction:
 [[ 0.08607629]
 [-1.4869082 ]
 [-0.926892  ]
 [-0.33498245]
 [-0.19840232]
 [-0.6372395 ]
 [-0.59024745]
 [-1.2443442 ]]
1672 Cost:  -1.6468647 
Prediction:
 [[ 0.08602932]
 [-1.4869599 ]
 [-0.9269352 ]
 [-0.33501634]
 [-0.19844285]
 [-0.63727736]
 [-0.59027606]
 [-1.2443748 ]]
1673 Cost:  -1.6469616 
Prediction:
 [[ 0.08598235]
 

1805 Cost:  -1.659792 
Prediction:
 [[ 0.07976642]
 [-1.4938844 ]
 [-0.93271136]
 [-0.33953792]
 [-0.20385352]
 [-0.64232355]
 [-0.5940888 ]
 [-1.248447  ]]
1806 Cost:  -1.6598895 
Prediction:
 [[ 0.07971928]
 [-1.4939367 ]
 [-0.9327549 ]
 [-0.33957198]
 [-0.20389429]
 [-0.6423616 ]
 [-0.5941175 ]
 [-1.2484776 ]]
1807 Cost:  -1.6599871 
Prediction:
 [[ 0.07967201]
 [-1.4939889 ]
 [-0.93279845]
 [-0.33960605]
 [-0.20393509]
 [-0.6423996 ]
 [-0.59414625]
 [-1.2485083 ]]
1808 Cost:  -1.6600847 
Prediction:
 [[ 0.07962486]
 [-1.494041  ]
 [-0.93284196]
 [-0.33964014]
 [-0.20397586]
 [-0.64243764]
 [-0.59417504]
 [-1.248539  ]]
1809 Cost:  -1.6601826 
Prediction:
 [[ 0.07957759]
 [-1.4940933 ]
 [-0.9328855 ]
 [-0.3396742 ]
 [-0.20401666]
 [-0.6424757 ]
 [-0.59420377]
 [-1.2485697 ]]
1810 Cost:  -1.6602803 
Prediction:
 [[ 0.07953045]
 [-1.4941455 ]
 [-0.9329291 ]
 [-0.3397083 ]
 [-0.20405743]
 [-0.64251375]
 [-0.5942325 ]
 [-1.2486004 ]]
1811 Cost:  -1.660378 
Prediction:
 [[ 0.07948318]
 [

1935 Cost:  -1.6725357 
Prediction:
 [[ 0.07361734]
 [-1.5006802 ]
 [-0.93838084]
 [-0.34397683]
 [-0.2091648 ]
 [-0.647277  ]
 [-0.5978314 ]
 [-1.2524433 ]]
1936 Cost:  -1.6726341 
Prediction:
 [[ 0.07356992]
 [-1.5007327 ]
 [-0.9384246 ]
 [-0.344011  ]
 [-0.20920572]
 [-0.64731514]
 [-0.5978603 ]
 [-1.2524742 ]]
1937 Cost:  -1.6727324 
Prediction:
 [[ 0.07352257]
 [-1.500785  ]
 [-0.9384682 ]
 [-0.34404522]
 [-0.20924664]
 [-0.64735335]
 [-0.5978891 ]
 [-1.252505  ]]
1938 Cost:  -1.6728308 
Prediction:
 [[ 0.07347515]
 [-1.5008372 ]
 [-0.93851185]
 [-0.34407943]
 [-0.20928758]
 [-0.64739156]
 [-0.597918  ]
 [-1.2525357 ]]
1939 Cost:  -1.6729293 
Prediction:
 [[ 0.07342774]
 [-1.5008898 ]
 [-0.9385556 ]
 [-0.34411365]
 [-0.20932853]
 [-0.6474297 ]
 [-0.59794676]
 [-1.2525666 ]]
1940 Cost:  -1.6730278 
Prediction:
 [[ 0.07338032]
 [-1.500942  ]
 [-0.9385992 ]
 [-0.34414786]
 [-0.20936945]
 [-0.64746785]
 [-0.5979756 ]
 [-1.2525973 ]]
1941 Cost:  -1.6731262 
Prediction:
 [[ 0.07333291]


# MNIST Dataset

In [20]:
#!pip install tensorflow-datasets

In [48]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from tensorflow.keras.utils import to_categorical
from tqdm import tqdm

In [49]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
nb_classes = 10

In [50]:
input_shape = X_train.shape[1] * X_train.shape[2]
X_train = X_train.reshape(-1, input_shape) 
y_train = to_categorical(y_train, nb_classes)

In [51]:
X_train = tf.image.convert_image_dtype(X_train, tf.float32)
y_train = tf.image.convert_image_dtype(y_train, tf.float32)
# X_test = tf.image.convert_image_dtype(X_test, tf.float32)
# y_test = tf.image.convert_image_dtype(y_test, tf.float32)

In [52]:
X = tf.placeholder("float", [None, 28*28])
Y = tf.placeholder("float", [None, nb_classes])

In [53]:
W = tf.Variable(tf.random_normal([784, nb_classes]), name = "Weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")

In [54]:
learning_rate = 0.1
training_epochs = 15
batch_size = 100

In [55]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate).minimize(cost)

In [56]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

C:\Users\since\anaconda3\lib\site-packages\tensorflow\python\client\session.py:1766: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [57]:
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(60000 / batch_size)
    
    for i in tqdm(range(total_batch)):
        # batch_xs, batch_ys는 각각 train data에서 batch_size 개수 만큼 뽑아내는 것을 말함
        batch_xs, batch_ys = X_train[(i*batch_size):batch_size+(i*batch_size)].eval(), y_train[(i*batch_size):batch_size+(i*batch_size)].eval()
        c, _ = sess.run([cost, optimizer], feed_dict={X: batch_xs, Y:batch_ys})
        avg_cost += c / total_batch
        
    print("Epoch", "%04d" % (epoch + 1), "cost =", "{:.9f}".format(avg_cost))

100%|██████████| 600/600 [05:12<00:00,  1.92it/s]


Epoch 0001 cost = 2.531715827


100%|██████████| 600/600 [06:26<00:00,  1.55it/s]


Epoch 0002 cost = 0.993807222


100%|██████████| 600/600 [07:33<00:00,  1.32it/s]


Epoch 0003 cost = 0.803614541


100%|██████████| 600/600 [08:42<00:00,  1.15it/s]


Epoch 0004 cost = 0.709012124


100%|██████████| 600/600 [09:14<00:00,  1.08it/s]


Epoch 0005 cost = 0.649035144


  6%|▌         | 34/600 [00:32<09:08,  1.03it/s]


KeyboardInterrupt: 